name: rust-crawler
on: [push]
jobs:
  build_and_test_app:
    runs-on: ubuntu-latest
    container: rust:1.36.0
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build app
        run: |
          rustup component add clippy
          rustup component add rustfmt
          cargo fmt --all -- --check
          cargo clippy
          cargo build --release --bin rust-crawler
